-- AlterEnum
ALTER TYPE "run_type" ADD VALUE 'ENRICHMENT';
ALTER TYPE "run_type" ADD VALUE 'INTAKE_PARSE';
ALTER TYPE "run_type" ADD VALUE 'DOCUMENT_CLASSIFY';
ALTER TYPE "run_type" ADD VALUE 'BUYER_OUTREACH_DRAFT';
ALTER TYPE "run_type" ADD VALUE 'ADVANCEMENT_CHECK';

-- AlterTable
ALTER TABLE "deals" ADD COLUMN "source" TEXT;
