import "server-only";

import { getGatewayClient } from "./gatewayClient.js";
import { validateSpatialSql } from "./sqlValidator.js";
import type {
  CartographerContext,
  GeoJsonFeature,
  GeoJsonFeatureCollection,
  CartographerAction,
} from "./types.js";

// ---------------------------------------------------------------------------
// spatialQuery — NL → spatial SQL → GeoJSON layer
//
// Flow:
// 1. The agent generates a SQL query from the user's natural-language request.
// 2. We validate the SQL (SELECT-only, allowlisted tables, LIMIT).
// 3. We execute via getGatewayClient().
// 4. We shape the rows into a GeoJSON FeatureCollection.
// 5. We return the layer + map actions.
// ---------------------------------------------------------------------------

export interface SpatialQueryInput {
  /** The SQL query generated by the agent from the user's NL request. */
  sql: string;
  /** Human-readable label for the resulting layer. */
  layerLabel?: string;
  /** Optional style overrides for the map layer. */
  style?: {
    fillColor?: string;
    fillOpacity?: number;
    lineColor?: string;
    lineWidth?: number;
  };
}

export interface SpatialQueryResult {
  layerId: string;
  featureCollection: GeoJsonFeatureCollection;
  rowCount: number;
  sqlExecuted: string;
  mapActions: CartographerAction[];
  citationRefs: string[];
}

/**
 * Execute a validated spatial query and return a renderable GeoJSON layer.
 */
export async function executeSpatialQuery(
  ctx: CartographerContext,
  input: SpatialQueryInput,
): Promise<SpatialQueryResult> {
  // ---- Validate ----
  const validation = validateSpatialSql(input.sql);
  if (!validation.valid || !validation.sanitizedSql) {
    throw new Error(
      `Cartographer SQL validation failed: ${validation.errors.join("; ")}`,
    );
  }

  const sql = validation.sanitizedSql;

  // ---- Execute via gateway ----
  const gateway = getGatewayClient();
  const response = await gateway.sql(sql);
  const rows = Array.isArray(response.data)
    ? (response.data as Array<Record<string, unknown>>)
    : [];

  // ---- Shape into GeoJSON ----
  const features: GeoJsonFeature[] = rows
    .map((row, idx) => rowToFeature(row, idx))
    .filter((f): f is GeoJsonFeature => f !== null);

  const featureCollection: GeoJsonFeatureCollection = {
    type: "FeatureCollection",
    features,
  };

  const layerId = `cartographer-spatial-${Date.now()}`;
  const label = input.layerLabel ?? "Spatial Query Result";

  // ---- Build map actions ----
  const mapActions: CartographerAction[] = [
    {
      action: "add_layer",
      layerId,
      geojson: featureCollection,
      style: {
        paint: {
          "fill-color": input.style?.fillColor ?? "#3B82F6",
          "fill-opacity": input.style?.fillOpacity ?? 0.25,
          "line-color": input.style?.lineColor ?? "#2563EB",
          "line-width": input.style?.lineWidth ?? 2,
        },
      },
      label,
    },
  ];

  // If results exist, fly to the first feature's bbox
  if (features.length > 0) {
    const bbox = computeBBox(features);
    if (bbox) {
      mapActions.push({
        action: "fly_to",
        center: {
          lat: (bbox[1] + bbox[3]) / 2,
          lng: (bbox[0] + bbox[2]) / 2,
        },
        bbox,
      });
    }
  }

  const citationRefs = features
    .map((f) => f.properties.parcel_id ?? f.properties.id)
    .filter((id): id is string => typeof id === "string")
    .slice(0, 50);

  return {
    layerId,
    featureCollection,
    rowCount: features.length,
    sqlExecuted: sql,
    mapActions,
    citationRefs,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a database row into a GeoJSON Feature.
 * Looks for `geom`, `geometry`, `geojson`, or `wkt` columns.
 */
function rowToFeature(
  row: Record<string, unknown>,
  index: number,
): GeoJsonFeature | null {
  const geomCandidates = ["geom", "geometry", "geojson", "the_geom", "wkb_geometry"];
  let geometry: GeoJsonFeature["geometry"] | null = null;

  for (const key of geomCandidates) {
    const val = row[key];
    if (!val) continue;

    if (typeof val === "object" && (val as Record<string, unknown>).type) {
      geometry = val as GeoJsonFeature["geometry"];
      break;
    }

    if (typeof val === "string") {
      try {
        const parsed = JSON.parse(val);
        if (parsed && typeof parsed === "object" && parsed.type) {
          geometry = parsed as GeoJsonFeature["geometry"];
          break;
        }
      } catch {
        // Not JSON — might be WKT, skip for now
      }
    }
  }

  if (!geometry) return null;

  // Build properties from all non-geometry columns
  const properties: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(row)) {
    if (geomCandidates.includes(key)) continue;
    properties[key] = val;
  }
  properties._cartographer_row_index = index;

  return { type: "Feature", properties, geometry };
}

/**
 * Compute a bounding box [west, south, east, north] from a set of features.
 */
function computeBBox(
  features: GeoJsonFeature[],
): [number, number, number, number] | null {
  let minLng = Infinity;
  let minLat = Infinity;
  let maxLng = -Infinity;
  let maxLat = -Infinity;

  for (const feature of features) {
    visitCoordinates(feature.geometry.coordinates, (lng, lat) => {
      if (lng < minLng) minLng = lng;
      if (lng > maxLng) maxLng = lng;
      if (lat < minLat) minLat = lat;
      if (lat > maxLat) maxLat = lat;
    });
  }

  if (!Number.isFinite(minLng)) return null;
  return [minLng, minLat, maxLng, maxLat];
}

/** Recursively visit all [lng, lat] pairs in a GeoJSON coordinates structure. */
function visitCoordinates(
  coords: unknown,
  cb: (lng: number, lat: number) => void,
): void {
  if (!Array.isArray(coords)) return;
  if (typeof coords[0] === "number" && typeof coords[1] === "number") {
    cb(coords[0] as number, coords[1] as number);
    return;
  }
  for (const child of coords) {
    visitCoordinates(child, cb);
  }
}
