import "server-only";

import type { SqlValidationResult } from "./types.js";

// ---------------------------------------------------------------------------
// SQL validator — enforces SELECT-only, allowlisted tables, LIMIT
// ---------------------------------------------------------------------------

/**
 * Tables that Cartographer queries are allowed to reference.
 * Extend this set as new spatial tables are onboarded.
 */
const ALLOWED_TABLES = new Set([
  "ebr_parcels",
  "parcels",
  "parcel_geometries",
  "parcel_attributes",
  "zoning_districts",
  "flood_zones",
  "land_use",
  "road_network",
  "poi",
  "assessor_sales",
  "building_permits",
]);

/** Max rows any Cartographer query can return. */
const MAX_LIMIT = 500;
const DEFAULT_LIMIT = 100;

/** Dangerous SQL keywords that must never appear. */
const FORBIDDEN_KEYWORDS_RE =
  /\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|GRANT|REVOKE|EXEC|EXECUTE|MERGE|CALL|SET|PRAGMA|COPY|ATTACH)\b/i;

/** Detect semicolons that might chain statements (allow inside string literals). */
const MULTI_STATEMENT_RE = /;\s*\S/;

/**
 * Validate and sanitize a SQL string generated by the Cartographer agent.
 *
 * Rules:
 * 1. Must be a SELECT statement.
 * 2. Must not contain forbidden DDL/DML keywords.
 * 3. Must not contain multiple statements.
 * 4. All referenced tables must be in the allowlist.
 * 5. Must have a LIMIT clause ≤ MAX_LIMIT (one is injected if missing).
 */
export function validateSpatialSql(raw: string): SqlValidationResult {
  const errors: string[] = [];
  let sql = raw.trim();

  // Strip trailing semicolons
  while (sql.endsWith(";")) {
    sql = sql.slice(0, -1).trim();
  }

  // ---- Rule 1: must start with SELECT ----
  if (!/^\s*SELECT\b/i.test(sql)) {
    errors.push("Only SELECT statements are allowed.");
    return { valid: false, sanitizedSql: null, errors };
  }

  // ---- Rule 2: no forbidden keywords ----
  if (FORBIDDEN_KEYWORDS_RE.test(sql)) {
    const match = sql.match(FORBIDDEN_KEYWORDS_RE);
    errors.push(`Forbidden keyword detected: ${match?.[1] ?? "unknown"}.`);
    return { valid: false, sanitizedSql: null, errors };
  }

  // ---- Rule 3: no multi-statement ----
  if (MULTI_STATEMENT_RE.test(sql)) {
    errors.push("Multiple SQL statements are not allowed.");
    return { valid: false, sanitizedSql: null, errors };
  }

  // ---- Rule 4: all FROM/JOIN tables must be allowlisted ----
  const tableRefs = extractTableReferences(sql);
  const disallowed = tableRefs.filter((t) => !ALLOWED_TABLES.has(t.toLowerCase()));
  if (disallowed.length > 0) {
    errors.push(`Table(s) not in allowlist: ${disallowed.join(", ")}.`);
    return { valid: false, sanitizedSql: null, errors };
  }

  // ---- Rule 5: enforce LIMIT ----
  sql = enforceLimit(sql);

  return { valid: true, sanitizedSql: sql, errors };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Extract table names from FROM and JOIN clauses.
 * Intentionally simple regex — handles the common `FROM table` and `JOIN table` patterns.
 */
function extractTableReferences(sql: string): string[] {
  const tables: string[] = [];
  // Match FROM <table> and JOIN <table>, including optional schema prefix
  const re = /\b(?:FROM|JOIN)\s+(?:(\w+)\.)?(\w+)\b/gi;
  let match: RegExpExecArray | null;
  while ((match = re.exec(sql)) !== null) {
    const tableName = match[2];
    if (tableName && !/^(SELECT|WHERE|ON|AND|OR|AS|LEFT|RIGHT|INNER|OUTER|CROSS|FULL|LATERAL|NATURAL)$/i.test(tableName)) {
      tables.push(tableName);
    }
  }
  return tables;
}

/**
 * Ensure the query has a LIMIT clause no larger than MAX_LIMIT.
 */
function enforceLimit(sql: string): string {
  const limitMatch = sql.match(/\bLIMIT\s+(\d+)/i);
  if (limitMatch) {
    const requested = parseInt(limitMatch[1], 10);
    if (requested > MAX_LIMIT) {
      // Clamp to MAX_LIMIT
      return sql.replace(/\bLIMIT\s+\d+/i, `LIMIT ${MAX_LIMIT}`);
    }
    return sql;
  }
  // No LIMIT found — append default
  return `${sql} LIMIT ${DEFAULT_LIMIT}`;
}

/** Expose for testing. */
export const _testing = { extractTableReferences, enforceLimit, ALLOWED_TABLES, MAX_LIMIT };
